package com.mycompany.coffeemachineproject;

import com.mycompany.coffeemachineproject.Exception.*;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

public class CoffeeMachineGUI extends javax.swing.JFrame {

    CoffeeMachine cm = new CoffeeMachine();

    public CoffeeMachineGUI() {
        initComponents();
        // load the information from file about the containers, then pass them as paramerter to the cm
        //CoffeeMachine cm = new CoffeeMachine(.....);
        startMachine();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        dAmericanoRadioButton = new javax.swing.JRadioButton();
        dEspressoRadioButton = new javax.swing.JRadioButton();
        sEspressoRadioButton = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sAmericanoRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        grindLevelSlide = new javax.swing.JSlider();
        jLabel22 = new javax.swing.JLabel();
        cleanButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        beansContanierText = new javax.swing.JTextField();
        waterContainerText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffee Machine ");

        jLabel15.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel15.setText("  Please choose your coffee type: ");
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, null, java.awt.Color.white));

        jLabel16.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel16.setText("Americano");

        buttonGroup1.add(dAmericanoRadioButton);
        dAmericanoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dAmericanoRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(dEspressoRadioButton);
        dEspressoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dEspressoRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(sEspressoRadioButton);
        sEspressoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEspressoRadioButtonActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jLabel18.setText("Single");

        jLabel20.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jLabel20.setText("Double");

        jLabel17.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jLabel17.setText("Single");

        jLabel19.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jLabel19.setText("Double");

        jLabel21.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel21.setText("Espresso");

        buttonGroup1.add(sAmericanoRadioButton);
        sAmericanoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAmericanoRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(sEspressoRadioButton)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel17)
                                .addGap(4, 4, 4)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel20))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(dEspressoRadioButton))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(sAmericanoRadioButton)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(dAmericanoRadioButton))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel19))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel16)))
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sEspressoRadioButton)
                    .addComponent(dEspressoRadioButton)
                    .addComponent(sAmericanoRadioButton)
                    .addComponent(dAmericanoRadioButton))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(54, 54, 54))
        );

        jButton1.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jButton1.setText("Turn off");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        startButton.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        startButton.setText("Start");
        startButton.setEnabled(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        grindLevelSlide.setMajorTickSpacing(1);
        grindLevelSlide.setMaximum(10);
        grindLevelSlide.setMinimum(1);
        grindLevelSlide.setMinorTickSpacing(1);
        grindLevelSlide.setPaintLabels(true);
        grindLevelSlide.setPaintTicks(true);
        grindLevelSlide.setValue(5);

        jLabel22.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jLabel22.setText("  Grinde level ");
        jLabel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.gray));

        cleanButton.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        cleanButton.setText("clean");
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Beans Contanier ");

        jLabel2.setText("Water Container");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(startButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1))
                                    .addComponent(grindLevelSlide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(cleanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel22))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel15)))
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beansContanierText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(waterContainerText)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(beansContanierText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(waterContainerText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(grindLevelSlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cleanButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(startButton))
                        .addGap(47, 47, 47))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.getAccessibleContext().setAccessibleName(" ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sEspressoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEspressoRadioButtonActionPerformed
        // TODO add your handling code here:
        if (sEspressoRadioButton.isSelected())
            startButton.setEnabled(true);
    }//GEN-LAST:event_sEspressoRadioButtonActionPerformed

    private void dEspressoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dEspressoRadioButtonActionPerformed
        if (dEspressoRadioButton.isSelected())
            startButton.setEnabled(true);
    }//GEN-LAST:event_dEspressoRadioButtonActionPerformed

    private void sAmericanoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAmericanoRadioButtonActionPerformed
        if(sAmericanoRadioButton.isSelected())
            startButton.setEnabled(true);
    }//GEN-LAST:event_sAmericanoRadioButtonActionPerformed

    private void dAmericanoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dAmericanoRadioButtonActionPerformed
        if(dAmericanoRadioButton.isSelected())
            startButton.setEnabled(true);
    }//GEN-LAST:event_dAmericanoRadioButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
      int choice =0;
        if(sEspressoRadioButton.isSelected()){
            choice = 1;
        } else if (dEspressoRadioButton.isSelected()){
            choice =2;
        }else if (sAmericanoRadioButton.isSelected()){
            choice =3;
        }else if(dAmericanoRadioButton.isSelected()){
            choice = 4;
        }

        boolean needWater = false, needBeans = false;
        try{
            cm.brewer(choice,grindLevelSlide.getValue());
        }
        catch (WastedTrayException e) {
        JOptionPane.showMessageDialog(rootPane, """
            the wasted tray must be cleaning,
            If you want to clean it click the clean button,
            Other wise you cannot make your coffee""");
            startButton.setEnabled(false);
        } catch (OutOfBeansException e) {
            needBeans = true;
        } catch (OutOfWaterException e) {
            needWater = true;
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

        if (needBeans){
            do {
                try{
                    cm.getBeans().fill(beansHandel(cm));
                    break;
                }
                catch (BeansExceededCapacityException e) {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());
                }
            } while (true);    
        }
        if (needWater){
            String waterAmount = JOptionPane.showInputDialog(rootPane, """
                There isn't enough water\n
                Pleas enter the beans amount you want to add:""");
            try{
                cm.getWater().fill(Integer.parseInt(waterAmount));
            }
            catch (WaterExceededCapacityException e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }
        try {
            cm.getGrind().setGringLevle(grindLevelSlide.getValue());
        } catch (InvalidDataException ex) {
            
        }
        cm.getGrind().grinding();
        JOptionPane.showMessageDialog(rootPane,
            "The coffee cup has been made successfully!!"
            + "The caffeine amount in this cup in grams"
            + " = " + cm.getBeans().getCaffeine(choice));
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "You want to clean your teay?");
        startButton.setEnabled(true);
        WasteTray.level=0;
    }//GEN-LAST:event_cleanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeMachineGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beansContanierText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cleanButton;
    private javax.swing.JRadioButton dAmericanoRadioButton;
    private javax.swing.JRadioButton dEspressoRadioButton;
    private javax.swing.JSlider grindLevelSlide;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton sAmericanoRadioButton;
    private javax.swing.JRadioButton sEspressoRadioButton;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField waterContainerText;
    // End of variables declaration//GEN-END:variables
private void startMachine() {
        
        boolean needWater = false, needBeans = false;
        try {
            cm.start();
        } catch (WastedTrayException e) {
            JOptionPane.showMessageDialog(rootPane, """
                                           the wasted tray must be cleaning, 
                                           If you want to clean it click the clean button, 
                                           Other wise you cannot make your coffee""");
            startButton.setEnabled(false);
        } catch (EmptyBeansException e) {
           needBeans = true;
        } catch (EmptyWaterException e) {
           JOptionPane.showMessageDialog(rootPane, "The water container is empty");
           needWater = true;
        } catch (Exception e) {
           JOptionPane.showMessageDialog(rootPane, e.getMessage());
       }
        
        if (needBeans){
            String beansAmount = JOptionPane.showInputDialog(rootPane, """
                                                  The beans container is empty\n
                                                  Pleas enter the beans amount you want to add:""");
            try{
                cm.getBeans().fill(Integer.parseInt(beansAmount));
            }
            catch (BeansExceededCapacityException e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }
        if (needWater){
            String waterAmount = JOptionPane.showInputDialog(rootPane, """
                                                  The beans container is empty\n
                                                  Pleas enter the beans amount you want to add:""");
            try{
                cm.getWater().fill(Integer.parseInt(waterAmount));
            }
            catch (WaterExceededCapacityException e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }
    }

public int beansHandel(CoffeeMachine cm) {
        int beansAmount = 0;
        System.out.println("Enter the beans amount that you want to add measured in gram : ");
        do {
            try {
                String beansAmountInput = 
                JOptionPane.showInputDialog(rootPane, """
                There isn't enough\n
                Pleas enter the beans amount you want to add:""");
//                beansContanierText.getText();
                beansAmount = Integer.parseInt(beansAmountInput);
                if (beansAmount < 0 || beansAmount > cm.getBeans().getCapacity()) {
                    throw new InvalidDataException();
                }
                break;
            } catch (InputMismatchException e) {
                System.out.println("You have to enter a positave integer, try again: ");
            } catch (InvalidDataException ex) {
                System.out.println(ex.getMessage() +" must enter a positive number and not greater than the beans capacity ( "+cm.getBeans().getCapacity()+" ), Enter again");
            }
        } while (true);

        do {
            try {
                String input = JOptionPane.showInputDialog(this,"Enter the Arabica Percentage %, an integer from 1 to 100: ");
                double arabicaPercentage = Integer.parseInt(input);
                cm.getBeans().setArabicaPercentage(arabicaPercentage);
                JOptionPane.showMessageDialog(this, "So the Robusta Percentage %: " + (100 - arabicaPercentage) + "%");
                cm.getBeans().setRobustaPercentage(100-arabicaPercentage);
                break;
            } catch (InputMismatchException e) {
                System.out.println("You have to enter a positave integer, try again: ");
            } catch (InvalidDataException ex) {
                System.out.println(ex.getMessage() + ", must Enter number in range 0 to 100 ");
            }
        } while (true);
        return beansAmount;
    }
}
